import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import prisma from '../lib/prisma';
import Link from 'next/link';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Link href="/api/count" className={styles.description}>
          <code className={styles.code}>/api/count</code>
        </Link>
        <Link href="/api/findMany" className={styles.description}>
          <code className={styles.code}>/api/findMany</code>
        </Link>
        <Link href="/api/create" className={styles.description}>
          <code className={styles.code}>/api/create</code>
        </Link>
        <Link href="/api/findUnique" className={styles.description}>
          <code className={styles.code}>/api/findUnique</code>
        </Link>
        <Link href="/api/findUnique/90" className={styles.description}>
          <code className={styles.code}>/api/findUnique/90</code>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
