import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import prisma from '../lib/prisma';
import Link from 'next/link';
// import axios from 'axios';

import { getCsrfToken,useSession, signIn, signOut } from 'next-auth/react';
// import { getCsrfToken, useSession, signOut, signIn } from 'next-auth/clients';

const Home: NextPage = () => {
  // axios.get('/api/count').then((response) => console.log(response));
  const { data: session, status } = useSession();

  // console.log(session);
  // console.log(status);

  if (session) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <h1>Signed in as {session.user.name} </h1>
          <button onClick={() => signOut()}>Sign out</button>
          <Link passHref href="/">
          <p className={styles.description}>
            <code className={styles.code}>/Top Page</code>
          </p>
        </Link>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1> Not signed in...</h1>
        <button onClick={() => signIn()}>Sign in</button>{' '}
        <Link passHref href="/">
          <p className={styles.description}>
            <code className={styles.code}>/Top Page</code>
          </p>
        </Link>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );

  //   return (
  //     <>
  //       Signed in as {session.user.email} <br />
  //       <button onClick={() => signOut()}>Sign out</button>
  //     </>
  //   )
  // }
  // return (
  //   <>
  //     Not signed in <br />
  //     <button onClick={() => signIn()}>Sign in</button>
  //   </>
  // )
};

export default Home;
