version: "3"
services:

  mysqldb:
    build: ./mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: AccountManagement
      TZ: 'Asia/Tokyo'
      BIND-ADDRESS: 0.0.0.0
    volumes:
      - ./mysql/conf.d/:/etc/mysql/conf.d/
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_HOST: mysqldb
      ADMINER_DEFAULT_DB_NAME: AccountManagement